name: Aimen's React CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code from GitHub
      uses: actions/checkout@v2

    - name: Set Up Node.js Version
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Project Dependencies
      run: npm install

    - name: Lint the Code with ESLint
      run: npx eslint .

    - name: Docker Hub Login (Aimen's credentials)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create Docker Image
      run: |
        docker build -t aimen-docker-user/ci-aimen-app .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push aimen-docker-user/ci-aimen-app
